import 'package:flutter/material.dart';

import 'package:mp_ajjaks/models/sign_up.dart';

class SignUpPage extends StatelessWidget {
  const SignUpPage({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('MP-AJJAKS MEMBERSHIP FORM'),
      ),
      body: SignUpForm(), // We'll add this in a bit
    );
  }
}

class SignUpForm extends StatefulWidget {
  SignUpForm({Key? key}) : super(key: key);
  @override
  _SignUpFormState createState() => _SignUpFormState();
}

class _SignUpFormState extends State<SignUpForm> {
  final _formKey = GlobalKey<FormState>();
  SignUp member = new SignUp();
  String tehsil = 'Adhartal'; // new line
  String district = 'Agar'; // new line
  TextEditingController dateCtl = TextEditingController();

  @override
  Widget build(BuildContext context) {
    double w = MediaQuery.of(context).size.width;
    double h = MediaQuery.of(context).size.height;
    return GestureDetector(
      onTap: () {
        FocusManager.instance.primaryFocus?.unfocus();
      },
      child: Container(
        child: Form(
          key: _formKey,
          child: ListView(
            children: <Widget>[
              Column(
                children: [
                  TextFormField(
                    onSaved: (val) => member.name = val!,
                    decoration: InputDecoration(
                      labelText: 'Name:',
                      icon: Icon(Icons.person),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.mobileNumber = int.parse(val!),
                    keyboardType: TextInputType.number,
                    decoration: InputDecoration(
                      labelText: 'Mobile Number:',
                      icon: Icon(Icons.phone_sharp),
                    ),
                  ),

                  TextFormField(
                    controller: dateCtl,
                    decoration: InputDecoration(
                      labelText: "Date of birth:",
                      hintText: "Ex. Insert your dob",
                      icon: Icon(Icons.date_range),
                    ),
                    onTap: () async {
                      DateTime date = DateTime(1900);
                      FocusScope.of(context).requestFocus(new FocusNode());

                      date = (await showDatePicker(
                          context: context,
                          initialDate: DateTime.now(),
                          firstDate: DateTime(1900),
                          lastDate: DateTime(2100)))!;

                      dateCtl.text = date.toIso8601String();
                    },
                    onSaved: (val) => member.dob = val!,
                  ),

                  TextFormField(
                    onSaved: (val) => member.emailID = val!,
                    decoration: InputDecoration(
                      labelText: 'Email ID:',
                      icon: Icon(Icons.email),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.cast = val!,
                    decoration: InputDecoration(
                      labelText: 'Cast:',
                      icon: Icon(Icons.people),
                    ),
                  ),

                  TextFormField(
                    onSaved: (val) => member.subCast = val!,
                    decoration: InputDecoration(
                      labelText: 'Sub Cast:',
                      icon: Icon(Icons.people),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.religion = val!,
                    decoration: InputDecoration(
                      labelText: 'Religion:',
                      icon: Icon(Icons.people),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.password = val!,
                    obscureText: true,
                    decoration: InputDecoration(
                      labelText: 'Password:',
                      icon: Icon(Icons.password),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.whatsappNumber = int.parse(val!),
                    keyboardType: TextInputType.number,
                    decoration: InputDecoration(
                      labelText: 'Whatsapp Number:',
                      icon: Icon(Icons.whatsapp),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.ajjaksPost = val!,
                    decoration: InputDecoration(
                      labelText: 'MP-AJJAKS Post:',
                      icon: Icon(Icons.admin_panel_settings_rounded),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.departmentName = val!,
                    decoration: InputDecoration(
                      labelText: 'Department Name:',
                      icon: Icon(Icons.admin_panel_settings),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.departmentPost = val!,
                    decoration: InputDecoration(
                      labelText: 'Department Post:',
                      icon: Icon(Icons.admin_panel_settings_rounded),
                    ),
                  ),

                  // after the security code text field widget
                  DropdownButtonFormField<String>(
                    onSaved: (val) => member.tehsil = val!,
                    value: tehsil,
                    items: [
                      'Adhartal',
                      'Agar',
                      'Ajaygarh',
                      'Alirajpur',
                      'Alot',
                      'Amanganj',
                      'Amapatan',
                      'Amarwada',
                      'Ambah',
                      'Amla',
                      'Anjad',
                      'Anuppur',
                      'Aron',
                      'Ashoknagar',
                      'Ashta',
                      'Ater',
                      'Atner',
                      'Avantipur Badodiya',
                      'Babai',
                      'Bada Malhera',
                      'Badarwas',
                      'Badi',
                      'Badnagar',
                      'Badnawar',
                      'Badoda',
                      'Badoni',
                      'Badwah',
                      'Badwara',
                      'Bagli',
                      'Bahari',
                      'Bahoriband',
                      'Baihar',
                      'Bairad',
                      'Bajag',
                      'Bajna',
                      'Balaghat',
                      'Baldeogarh',
                      'Bamor',
                      'Bamori',
                      'Banda',
                      'Bandhavgarh',
                      'Bankhedi',
                      'Barely',
                      'Barghat',
                      'Barhi',
                      'Barode',
                      'Barwani',
                      'Batiagarh',
                      'Begumganj',
                      'Beohari',
                      'Berasia',
                      'Betul',
                      'Bhagwanpura',
                      'Bhainsdehi',
                      'Bhander',
                      'Bhanpura',
                      'Bhavra',
                      'Bhikangaon',
                      'Bhimpur',
                      'Bhind',
                      'Bhitarwar',
                      'Biaora',
                      'Bichiya',
                      'Bicholi Hapsi',
                      'Bichua',
                      'Bijawar',
                      'Bilaspur',
                      'Bina',
                      'Birpur',
                      'Birsa',
                      'Birsinghpur',
                      'Budhni',
                      'Burhanpur',
                      'Burhar',
                      'Buxwaha',
                      'Chachoura',
                      'Chand',
                      'Chanderi',
                      'Chandia',
                      'Chandla',
                      'Chaurai',
                      'Chhapra',
                      'Chhatarpur',
                      'Chhindwara',
                      'Chhindwara Nagar',
                      'Chicholi',
                      'Chinore',
                      'Chitrangi',
                      'Churhat',
                      'City Centre',
                      'Dabra',
                      'Dahi',
                      'Daloda',
                      'Damoh',
                      'Datia',
                      'Deori',
                      'Depalpur',
                      'Devendranagar',
                      'Devsar',
                      'Dewas',
                      'Dhanora',
                      'Dhar',
                      'Dharmapuri',
                      'Dhimarkheda',
                      'Dindori',
                      'Doleria',
                      'Dr. Ambedkar Nagar',
                      'Gadarwara',
                      'Gadwani',
                      'Gairatganj',
                      'Ganj Basoda',
                      'Garhakota',
                      'Gaurihar',
                      'Ghansor',
                      'Ghatigaon',
                      'Ghatiya',
                      'Ghodadongri',
                      'Ghughri',
                      'Ghuwara',
                      'Gogawaan',
                      'Gohad',
                      'Gohapur',
                      'Goharganj',
                      'Gopad Banas Sidhi',
                      'Gorakhpur',
                      'Gormi',
                      'Gotegaon',
                      'Goth',
                      'Gulabganj',
                      'Gulana',
                      'Guna',
                      'Gunnor',
                      'Gurh',
                      'Gwalior',
                      'Gyaraspur',
                      'Handia',
                      'Hanumana',
                      'Harda',
                      'Harrai',
                      'Harsud',
                      'Hatod',
                      'Hatpipliya',
                      'Hatta',
                      'Hoshangabad',
                      'Huzoor Rural',
                      'Huzoor Urban',
                      'Huzur',
                      'Ichhawar',
                      'Indergarh',
                      'Isagarh',
                      'Itarsi',
                      'Jabalpur',
                      'Jabera',
                      'Jaisinagar',
                      'Jaisinghnagar',
                      'Jaithari',
                      'Jaitpur',
                      'Jaora',
                      'Jatara',
                      'Jawa',
                      'Jawad',
                      'Jawar',
                      'Jhabua',
                      'Jharda',
                      'Jhirniya',
                      'Jiran',
                      'Jobat',
                      'Joura',
                      'Junnardeo',
                      'Kailaras',
                      'Kalapipal',
                      'Kanadiya',
                      'Kannod',
                      'Karahal',
                      'Kareli',
                      'Karera',
                      'Karkeli',
                      'Kasrawad',
                      'Katangi',
                      'Katni',
                      'Katni Rural',
                      'Katthiwada',
                      'Kesli',
                      'Kevlari',
                      'Khachrod',
                      'Khairlanji',
                      'Khaknar',
                      'Khalwa',
                      'Khandwa',
                      'Khaniadhana',
                      'Khargapur',
                      'Khargone',
                      'Khargone Nagar',
                      'Khategaon',
                      'Khilchipur',
                      'Khirkiya',
                      'Khudail',
                      'Khujner',
                      'Khurai',
                      'Kirnapur',
                      'Kolar',
                      'Kolaras',
                      'Kotar',
                      'Kothi',
                      'Kotma',
                      'Kukshi',
                      'Kumbhraj',
                      'Kundam',
                      'Kurai Kurai',
                      'Kurwai',
                      'Kusmi',
                      'Lahar',
                      'Lakhanadon',
                      'Lalbarra',
                      'Lanji',
                      'Laundi',
                      'Lidhora',
                      'Mada',
                      'Maharajpur',
                      'Maheshwar',
                      'Maihar',
                      'Majhauli',
                      'Majhgawan',
                      'Majoli',
                      'Makdone',
                      'Maksudangarh',
                      'Malharganj',
                      'Malhargarh',
                      'Malthone',
                      'Manasa',
                      'Manawar',
                      'Mandla',
                      'Mandsaur',
                      'Mangawan',
                      'Manpur',
                      'Mau',
                      'Mauganj',
                      'Meghnagar',
                      'Mehgaon',
                      'Mehidpur',
                      'Mihona',
                      'Mohan',
                      'Mohangarh',
                      'Mohkhed',
                      'Morena Rural',
                      'Morena Urban',
                      'Multai',
                      'Mungaoli',
                      'Murar',
                      'Nagda',
                      'Nagod',
                      'Nai Garhi',
                      'Nai Sarai',
                      'Nainpur',
                      'Nalkheda',
                      'Narayanganj',
                      'Narsinghgarh',
                      'Narsinghpur',
                      'Narwar',
                      'Nasrullaganj',
                      'Nateran',
                      'Neemuch',
                      'Neemuch Nagar',
                      'Nepanagar',
                      'Nivas',
                      'Niwali',
                      'Niwari',
                      'Nowgong',
                      'Nowrozabad',
                      'Old Indore',
                      'Orchha',
                      'Pachore',
                      'Palera',
                      'Pali',
                      'Panagar',
                      'Pandhana',
                      'Pandurna',
                      'Panna',
                      'Pansemal',
                      'Paraswada',
                      'Parsia',
                      'Patan',
                      'Patera',
                      'Pathari',
                      'Patharia',
                      'Pati',
                      'Pawai',
                      'Petlavad',
                      'Pichhore',
                      'Piparai',
                      'Pipariya',
                      'Piploda',
                      'Pithampur',
                      'Pohari',
                      'Polay Kalan',
                      'Porsa',
                      'Prabhat Pattan',
                      'Prithvipur',
                      'Punasa',
                      'Pushprajgarh',
                      'Raghogarh',
                      'Raghurajnagar Rural',
                      'Raghurajnagar Urban',
                      'Rahatgaon',
                      'Rahatgarh',
                      'Raipur',
                      'Raipura',
                      'Raisen',
                      'Rajgarh',
                      'Rajnagar',
                      'Rajpur',
                      'Rama',
                      'Ramnagar',
                      'Rampur',
                      'Rampur Naikin',
                      'Rampura',
                      'Ranapur',
                      'Ranjhi',
                      'Raoti',
                      'Ratlam',
                      'Ratlam Rural',
                      'Rau',
                      'Reethi',
                      'Rehli',
                      'Rehti',
                      'Roun',
                      'Sabalgarh',
                      'Sagar',
                      'Sailana',
                      'Sainkheda',
                      'Sanawad',
                      'Sanwer',
                      'Sarai',
                      'Sarangpur',
                      'Sardarpur',
                      'Satwas',
                      'Sauser',
                      'Segaon',
                      'Sehore (Rural)',
                      'Sehore (Urban)',
                      'Semaria',
                      'Sendhwa',
                      'Seondha',
                      'Seoni Gramin',
                      'Seoni Malwa',
                      'Seoni',
                      'Shadora',
                      'Shahdol',
                      'Shahgarh',
                      'Shahnagar',
                      'Shahpur',
                      'Shahpura',
                      'Shajapur',
                      'Shamgarh',
                      'Shamshabad',
                      'Sheopur',
                      'Shivpuri',
                      'Shujalpur',
                      'Shyampur',
                      'Sihawal',
                      'Sihora',
                      'Silvani',
                      'Simariya',
                      'Singoli',
                      'Singrauli Urban',
                      'Singrauli Waidhan',
                      'Sirali',
                      'Sirmaur',
                      'Sironj',
                      'Sohagpur',
                      'Sondwa',
                      'Sonkatch',
                      'Sultanpur',
                      'Susner',
                      'Suthaliya',
                      'Suvasara',
                      'Tal',
                      'Tamiya',
                      'Tansen',
                      'Tarana',
                      'Tendukheda',
                      'Teonthar',
                      'Thandla',
                      'Thikri',
                      'Tikamgarh',
                      'Timarni',
                      'Tonk Khurd',
                      'Tyonda',
                      'Udaipura',
                      'Ujjain',
                      'Ujjain Kothi Mahal',
                      'Ujjain Rural',
                      'Umreth',
                      'Unchehra',
                      'Vidisha Rural',
                      'Vidisha Urban',
                      'Vijaypur',
                      'Vijayraghavgarh',
                      'Waraseoni',
                      'Warla',
                      'Zirapur'
                    ].map<DropdownMenuItem<String>>(
                      (String val) {
                        return DropdownMenuItem(
                          child: Text(val),
                          value: val,
                        );
                      },
                    ).toList(),
                    onChanged: (val) {
                      setState(() {
                        tehsil = val!;
                      });
                    },
                    decoration: InputDecoration(
                      labelText: 'Tehsil:',
                      icon: Icon(Icons.location_city),
                    ),
                  ),

                  // after the security code text field widget
                  DropdownButtonFormField<String>(
                    onSaved: (val) => member.district = val!,
                    value: district,
                    items: [
                      'Agar',
                      'Alirajpur',
                      'Anuppur',
                      'Ashoknagar',
                      'Balaghat',
                      'Barwani',
                      'Betul',
                      'Bhind',
                      'Bhopal',
                      'Burhanpur',
                      'Chhatarpur',
                      'Chhindwara',
                      'Damoh',
                      'Datia',
                      'Dewas',
                      'Dhar',
                      'Dindori',
                      'Guna',
                      'Gwalior',
                      'Harda',
                      'Hoshangabad',
                      'Indore',
                      'Jabalpur',
                      'Jhabua',
                      'Katni',
                      'Khandwa',
                      'Khargone',
                      'Malwa',
                      'Mandla',
                      'Mandsaur',
                      'Morena',
                      'Narsinghpur',
                      'Neemuch',
                      'Panna',
                      'Raisen',
                      'Rajgarh',
                      'Ratlam',
                      'Rewa',
                      'Sagar',
                      'Satna',
                      'Sehore',
                      'Seoni',
                      'Shahdol',
                      'Shajapur',
                      'Sheopur',
                      'Shivpuri',
                      'Sidhi',
                      'Singrauli',
                      'Tikamgarh',
                      'Ujjain',
                      'Umaria',
                      'Vidisha'
                    ].map<DropdownMenuItem<String>>(
                      (String val) {
                        return DropdownMenuItem(
                          child: Text(val),
                          value: val,
                        );
                      },
                    ).toList(),
                    onChanged: (val) {
                      setState(() {
                        district = val!;
                      });
                    },
                    decoration: InputDecoration(
                      labelText: 'District:',
                      icon: Icon(Icons.pin_drop),
                    ),
                  ),

                  TextFormField(
                    onSaved: (val) => member.address = val!,
                    decoration: InputDecoration(
                      labelText: 'Current Address:',
                      icon: Icon(Icons.pin_drop),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.address = val!,
                    decoration: InputDecoration(
                      labelText: 'Permanent Address:',
                      icon: Icon(Icons.pin_drop),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.pincode = int.parse(val!),
                    keyboardType: TextInputType.number,
                    decoration: InputDecoration(
                      labelText: 'Pincode:',
                      icon: Icon(Icons.pin_drop),
                    ),
                  ),

                  TextFormField(
                    onSaved: (val) => member.bloodGroup = val!,
                    decoration: InputDecoration(
                      labelText: 'blood group:',
                      icon: Icon(Icons.bloodtype),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.education = val!,
                    decoration: InputDecoration(
                      labelText: 'Education:',
                      icon: Icon(Icons.cast_for_education),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.speciality = val!,
                    decoration: InputDecoration(
                      labelText: 'Speciality:',
                      icon: Icon(Icons.cast_for_education),
                    ),
                  ),
                  TextFormField(
                    onSaved: (val) => member.contribution = val!,
                    decoration: InputDecoration(
                      labelText: 'Contribution for Community:',
                      icon: Icon(Icons.cast_for_education),
                    ),
                  ),

                  TextFormField(
                    onSaved: (val) => member.declaration = val!,
                    decoration: InputDecoration(
                      labelText: 'Declaration:',
                      icon: Icon(Icons.person),
                    ),
                  ),
                ],
              ),
              SizedBox(
                height: 20,
              ),
              Container(
                width: w * 0.5,
                height: h * 0.08,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(30),
                  image: DecorationImage(
                      image: AssetImage("img/loginButton.png"),
                      fit: BoxFit.cover),
                ),
                child: Center(
                  child: Text(
                    "Sign up",
                    style: TextStyle(
                      fontSize: 36,
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                    ),
                  ),
                ),
              ),
              // we will work in here
            ],
          ),
        ),
      ),
    );
  }
}
